name: Feature Request
about: Yeni özellik öner
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Hangi problemi çözüyor
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Önerilen çözüm
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatifler
